from enum import Enum


class UserSlot(str, Enum):
    USER_PREFERENCES = "ASK_USER_PREFERENCES"
    USER_BUDGET = "ASK_USER_BUDGET"
    DELIVERY_ADDRESS = "ASK_DELIVERY_ADDRESS"
    PRODUCT_NAME = "ASK_PRODUCT_NAME"
    USE_CASE = "ASK_USE_CASE"
    PRODUCTS_TO_COMPARE = "ASK_PRODUCTS_TO_COMPARE"
    QUANTITY = "ASK_QUANTITY"
    ORDER_ID = "ASK_ORDER_ID"
    MODIFICATION_TYPE = "ASK_MODIFICATION_TYPE"
    RETURN_REASON = "ASK_RETURN_REASON"


class BackendFunction(str, Enum):
    FETCH_PRODUCT_INVENTORY = "FETCH_PRODUCT_INVENTORY"
    FETCH_PURCHASE_HISTORY = "FETCH_PURCHASE_HISTORY"
    FETCH_USER_PROFILE = "FETCH_USER_PROFILE"
    FETCH_PRODUCT_DETAILS = "FETCH_PRODUCT_DETAILS"
    FETCH_SIMILAR_PRODUCTS = "FETCH_SIMILAR_PRODUCTS"
    FETCH_PRODUCT_REVIEWS = "FETCH_PRODUCT_REVIEWS"


class QueryIntent(str, Enum):
    PRODUCT_SEARCH = "product_search"
    RECOMMENDATION = "recommendation"
    PRICE_INQUIRY = "price_inquiry"
    PURCHASE = "purchase"
    ORDER_STATUS = "order_status"
    PRODUCT_COMPARISON = "product_comparison"
    GENERAL_HELP = "general_help"


class ResponseType(str, Enum):
    QUESTION = "question"
    FINAL_ANSWER = "final_answer"
    ERROR = "error"



ShoppingFunction = BackendFunction